In [1]:
import pandas as pd
import os

In [2]:
df1 = pd.read_csv("./data_csv/FaelleZeitreihe.csv", sep=";")
df1.head()

   Jahr  Anzahl erfasste Faelle Aufklaerungsquote
0  1987                 4444108              44,2
1  1988                 4356726              45,9
2  1989                 4358573              47,2
3  1990                 4455333                47
4  1991                 4752175              45,4

In [3]:
df2 = pd.read_csv("./data_csv/ZR-F-01-T01-Faelle_csv.csv",
                  sep=";",
                  #decimal=",",
                  encoding="latin_1",
                  header=1)

df2.replace(',','', regex=True, inplace=True)
df2.head()

,Schluessel,Straftat,Jahr,erfasste Faelle,HZ,Versuche - Anzahl,Versuche - Anteil in %,mit Schusswaffe gedroht,mit Schusswaffe geschossen,Aufklaerungsquote in %,Tatverdaechtige insgesamt,Nichtdeutsche Tatverdaechtige - Anzahl,Nichtdeutsche Tatverdaechtige - Anteil in %
0,------,Straftaten insgesamt,1987,4444108,7268.70,382623,8.6,6564,5429,44.2,1290441,258329,20.0
1,------,Straftaten insgesamt,1988,4356726,7114.40,371110,8.5,6639,4976,45.9,1314080,286741,21.8
2,------,Straftaten insgesamt,1989,4358573,7062.40,363650,8.3,6294,4633,47.2,1370962,336016,24.5
3,------,Straftaten insgesamt,1990,4455333,7108.20,352518,7.9,6589,4185,47.0,1437923,383583,26.7
4,------,Straftaten insgesamt,1991,4752175,7310.90,373651,7.9,7959,4543,45.4,1466752,405545,27.6

In [4]:
for col in list(df2.columns)[2:]:
    df2[col] = pd.to_numeric(df2[col],  errors='coerce')

In [7]:
df2_store_path = "data_json/ZR-F-01-T01-Faelle_json.json"
df2_full_path = os.path.join(os.getcwd(), df2_store_path)

f = open(df2_full_path, "w")
f.write("")
f.close()

df2.to_json(df2_full_path, orient="records", force_ascii=False)

In [8]:
df2[["Straftat", "Jahr", "erfasste Faelle"]]

                                        Straftat  Jahr  erfasste Faelle
0                           Straftaten insgesamt  1987          4444108
1                           Straftaten insgesamt  1988          4356726
2                           Straftaten insgesamt  1989          4358573
3                           Straftaten insgesamt  1990          4455333
4                           Straftaten insgesamt  1991          4752175
...                                          ...   ...              ...
12916  Sachbeschädigung durch Graffiti insgesamt  2016           105094
12917  Sachbeschädigung durch Graffiti insgesamt  2017           103997
12918  Sachbeschädigung durch Graffiti insgesamt  2018            97610
12919  Sachbeschädigung durch Graffiti insgesamt  2019            96244
12920  Sachbeschädigung durch Graffiti insgesamt  2020           109441

[12921 rows x 3 columns]

In [27]:
# Liste mit allen erfassten Straftaten, sortiert nach Fallzahl insgesamt
df2[["Straftat", "erfasste Faelle"]].groupby("Straftat").sum("erfasste Faelle").sort_values("erfasste Faelle", ascending=False).head(30)

                                                    erfasste Faelle
Straftat
Straftaten insgesamt                                      201748882
Straftaten insgesamt jedoch ohne Verstöße gegen...         66087567
Diebstahl insgesamt und zwar:                              62008848
Straßenkriminalität                                        51300802
Sonstige Straftatbestände (StGB)                           36433058
Diebstahl insgesamt                                        32318732
Vermögens- und Fälschungsdelikte                           32085194
Diebstahl ohne erschwerende Umstände §§ 242 247...         31978992
Diebstahl unter erschwerenden Umständen §§ 243-...         30029856
in/aus Warenhäusern Verkaufsräumen Selbstbedien...         29122876
Straftaten insgesamt jedoch ohne Verstöße gegen...         27293726
in/aus Kraftfahrzeugen                                     26462738
Rohheitsdelikte und Straftaten gegen die persön...         21310736
Alle sonstigen Straftaten gemäß StGB - ohne Ver...         20265872
Betrug §§ 263 263a 264 264a 265 265a 265b StGB ...         19384041
Sachbeschädigung §§ 303-305a StGB darunter:                16843677
Strafrechtliche Nebengesetze                               15766249
Ladendiebstahl insgesamt                                   15755479
Einfacher Ladendiebstahl                                   15378146
Diebstahl ohne erschwerende Umstände §§ 242 247...         12981791
Diebstahl insgesamt von Fahrrädern einschl. unb...         12817512
Diebstahl unter erschwerenden Umständen § 243 2...          9984663
Diebstahl unter erschwerenden Umständen §§ 243-...          9352279
Körperverletzung §§ 223-227 229 231 StGB davon:             8843428
Sachbeschädigung an Kfz                                     8138989
Rauschgiftkriminalität darunter:                            7450259
(Vorsätzliche leichte) Körperverletzung § 223 StGB          7076237
Alle sonstigen Straftaten gemäß StGB - ohne Ver...          6299030
von Fahrrädern einschl. unbefugte Ingebrauchnahme           6105419
Gewaltkriminalität                                          6017637

In [66]:
# Liste aller Straftaten, welche "straftat_str" inbehalten, sortiert nach Fallzahl insgesamt

"""
Straftatenliste:
"Gewaltkriminalität"
"Rauschgiftkriminalität darunter:"
"Sachbeschädigung §§ 303-305a StGB darunter:" + "Sachbeschädigung §§ 303-305a StGB"
contains "Betrug §§ 263" + "sonstiger Betrug darunter:" + contains "Sonstiger Betrug"
"Diebstahl insgesamt" + "Diebstahl insgesamt und zwar:"
"Sonstige Straftatbestände (StGB)"
"""

straftat_str = "Diebstahl"

df2[["Straftat", "erfasste Faelle"]][df2["Straftat"].str.contains(straftat_str)].groupby("Straftat").sum("erfasste Faelle").sort_values("erfasste Faelle", ascending=False)

                                                    erfasste Faelle
Straftat
Diebstahl insgesamt und zwar:                              62008848
Diebstahl insgesamt                                        32318732
Diebstahl ohne erschwerende Umstände §§ 242 247...         31978992
Diebstahl unter erschwerenden Umständen §§ 243-...         30029856
Diebstahl ohne erschwerende Umstände §§ 242 247...         12981791
...                                                             ...
Einfacher Diebstahl von Rezeptformularen zur Er...             1157
Schwerer Diebstahl von Betäubungsmitteln bei He...              411
Einfacher Diebstahl von Betäubungsmitteln aus A...              307
Einfacher Diebstahl von Betäubungsmitteln aus A...              249
Einfacher Diebstahl von Betäubungsmitteln bei H...              238

[78 rows x 1 columns]

In [15]:
# Auflistung jährlicher Fallzahlen für straftat_str
straftat_str = "Straßenkriminalität"
df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == straftat_str]

                  Straftat  Jahr erfasste Faelle
12879  Straßenkriminalität  1989         1568420
12880  Straßenkriminalität  1990         1620009
12881  Straßenkriminalität  1991         1753323
12882  Straßenkriminalität  1992         1938031
12883  Straßenkriminalität  1993         2383944
12884  Straßenkriminalität  1994         2231527
12885  Straßenkriminalität  1995         2195351
12886  Straßenkriminalität  1996         2032542
12887  Straßenkriminalität  1997         1920414
12888  Straßenkriminalität  1998         1799105
12889  Straßenkriminalität  1999         1740270
12890  Straßenkriminalität  2000         1658026
12891  Straßenkriminalität  2001         1693746
12892  Straßenkriminalität  2002         1795355
12893  Straßenkriminalität  2003         1754283
12894  Straßenkriminalität  2004         1718141
12895  Straßenkriminalität  2005         1621978
12896  Straßenkriminalität  2006         1557626
12897  Straßenkriminalität  2007         1568124
12898  Straßenkriminalität  2008         1490158
12899  Straßenkriminalität  2009         1435655
12900  Straßenkriminalität  2010         1352897
12901  Straßenkriminalität  2011         1382949
12902  Straßenkriminalität  2012         1357134
12903  Straßenkriminalität  2013         1309807
12904  Straßenkriminalität  2014         1342905
12905  Straßenkriminalität  2015         1329070
12906  Straßenkriminalität  2016         1316866
12907  Straßenkriminalität  2017         1203124
12908  Straßenkriminalität  2018         1131088
12909  Straßenkriminalität  2019         1075143
12910  Straßenkriminalität  2020         1023791

In [55]:
# Auflistung jährlicher Fallzahlen für straftat_str
straftat_str = "Betrug"
df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains(straftat_str)][df2["Jahr"]>2013].groupby("Straftat").sum("erfasste Faelle").sort_values("erfasste Faelle", ascending=False)

C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/1490248230.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains(straftat_str)][df2["Jahr"]>2013].groupby("Straftat").sum("erfasste Faelle").sort_values("erfasste Faelle", ascending=False)

                                                     Jahr  erfasste Faelle
Straftat
Betrug §§ 263 263a 264 264a 265 265a-e StGB          6057          2481823
Betrug §§ 263 263a 264 264a 265 265a 265b StGB       4029          1935192
Betrug §§ 263 263a 264 264a 265 265a 265b StGB       4033          1809395
Sonstiger Betrug                                    10090          1339046
Sonstige weitere Betrugsarten                       14119          1042420
Sonstiger Betrug                                     4029           618795
Betrug bzw. Computerbetrug mittels rechtswidrig...  10090           324187
Wirtschaftskriminalität bei Betrug                  14119           209527
Betrug mittels rechtswidrig erlangter unbarer Z...   4029           138151
Betrug bzw. Computerbetrug mittels rechtswidrig...  10090            90863
Betrug mittels rechtswidrig erlangter Zahlungsk...  10090            82062
Betrug und Untreue im Zusammenhang mit Beteilig...  14119            64937
Betrug mittels rechtswidrig erlangter Debitkart...   4029            47460
Betrug bzw. Computerbetrug mittels rechtswidrig...  10090            37411
Betrug mittels rechtswidrig erlangter Debitkart...   4029            34556
Betrug mittels rechtswidrig erlangter Daten von...   4029            32005
Betrug z.N.v. Versicherungen und Versicherungsm...  14119            27072
Betrug mittels rechtswidrig erlangter Kreditkarten   4029            17345
Betrug mittels rechtswidrig erlangter sonstige ...   4029             6785
Betrug z.N.v. Sozialversicherungen und Sozialve...   4029             6710
Betrug mit Zugangsberechtigungen zu Kommunikati...   4029             3932
Betrug bei Börsenspekulationen                       4029               23

In [101]:
# Tabelle generieren mit Spalten [Straftat, Jahr, Fallzahlen]

"""
Straftatenliste:
"Gewaltkriminalität"
"Rauschgiftkriminalität darunter:"
"Sachbeschädigung §§ 303-305a StGB darunter:" + "Sachbeschädigung §§ 303-305a StGB"
contains "Betrug §§ 263" + "sonstiger Betrug darunter:" + contains "Sonstiger Betrug"
"Diebstahl insgesamt" + "Diebstahl insgesamt und zwar:"
"Sonstige Straftatbestände (StGB)"
"""

df3_1 = pd.DataFrame()
df3_1 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Gewaltkriminalität"][df2["Jahr"] >= 1993]

df3_2 = pd.DataFrame()
df3_2 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Rauschgiftkriminalität darunter:"][df2["Jahr"] >= 1993]

df3_2["Straftat"] = "Rauschgiftkriminalität"

df3_3 = pd.DataFrame()
df3_3 = df2[["Straftat",
             "Jahr",
             "erfasste Faelle"]][df2["Straftat"].isin(["Sachbeschädigung §§ 303-305a StGB darunter:",
                                                       "Sachbeschädigung §§ 303-305a StGB"])][df2["Jahr"] >= 1993]

df3_3["Straftat"] = "Sachbeschädigung"

df3_4_a = pd.DataFrame()
df3_4_a = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains("Betrug §§ 263")][df2["Jahr"] >= 1993]

df3_4_a["Straftat"] = "Betrug"

df3_4_b = pd.DataFrame()
df3_4_b = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "sonstiger Betrug darunter:"][df2["Jahr"] >= 1993]

df3_4_b["Straftat"] = "Betrug"

df3_4_c = pd.DataFrame()
df3_4_c = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains("Sonstiger Betrug")][df2["Jahr"] >= 1993]

df3_4_c["Straftat"] = "Betrug"

df3_4 = pd.concat([df3_4_a, df3_4_b, df3_4_c]).groupby(["Straftat", "Jahr"]).sum().reset_index()

df3_5 = pd.DataFrame()
df3_5 = df2[["Straftat",
             "Jahr",
             "erfasste Faelle"]][df2["Straftat"].isin(["Diebstahl insgesamt",
                                                       "Diebstahl insgesamt und zwar:"])][df2["Jahr"] >= 1993]

df3_5["Straftat"] = "Diebstahl"

df3_6 = pd.DataFrame()
df3_6 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Sonstige Straftatbestände (StGB)"][df2["Jahr"] >= 1993]

df3_6["Straftat"] = "Sonstige"

df3 = pd.concat([df3_1, df3_2, df3_3, df3_4, df3_5, df3_6]).groupby(["Straftat", "Jahr"]).sum().reset_index()
df3

C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_1 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Gewaltkriminalität"][df2["Jahr"] >= 1993]
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_2 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Rauschgiftkriminalität darunter:"][df2["Jahr"] >= 1993]
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:22: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_3 = df2[["Straftat",
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:30: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_4_a = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains("Betrug §§ 263")][df2["Jahr"] >= 1993]
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_4_b = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "sonstiger Betrug darunter:"][df2["Jahr"] >= 1993]
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:40: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_4_c = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"].str.contains("Sonstiger Betrug")][df2["Jahr"] >= 1993]
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:47: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_5 = df2[["Straftat",
C:\Users\jonas\AppData\Local\Temp/ipykernel_24064/2069370262.py:55: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_6 = df2[["Straftat", "Jahr", "erfasste Faelle"]][df2["Straftat"] == "Sonstige Straftatbestände (StGB)"][df2["Jahr"] >= 1993]

     Straftat  Jahr  erfasste Faelle
0      Betrug  1993           787390
1      Betrug  1994           860745
2      Betrug  1995           895034
3      Betrug  1996           950956
4      Betrug  1997           976116
..        ...   ...              ...
163  Sonstige  2016          1143128
164  Sonstige  2017          1096977
165  Sonstige  2018          1102248
166  Sonstige  2019          1107007
167  Sonstige  2020          1150750

[168 rows x 3 columns]

In [107]:
df3_store_path = "data_json/ZR-F-01-T01-Faelle_filtered_json.json"
df3_full_path = os.path.join(os.getcwd(), df3_store_path)

f = open(df2_full_path, "w")
f.write("")
f.close()

df3.to_json(df3_full_path, orient="records", force_ascii=False)

In [109]:
df3.Straftat.unique()

array(['Betrug', 'Diebstahl', 'Gewaltkriminalität',
       'Rauschgiftkriminalität', 'Sachbeschädigung', 'Sonstige'],
      dtype=object)